### ISSUE TITLE
安全问题

### ISSUE THREAD

**Issue by Minty-He** [wxiaoqi/Spring-Cloud-Platform#37]
开源版本存在严重的安全问题，微服务网关ace-gate的访问控制能被绕过，攻击者可获得签发jwt的私钥以任意用户身份登录。
希望能和作者邮件沟通下漏洞细节和修复方案。

**Comment by wxiaoqi** [comment]
可以提供下具体的私钥获取过程，我这边来Fix

**Comment by Minty-He** [comment]
dump出JVM堆内存
![image2020-8-7 16 54 4](https://user-images.githubusercontent.com/25167192/89852791-38204a00-dbc2-11ea-8a53-c924531f85b9.png)

OQL查询
`SELECT userPriKey FROM ".*KeyConfiguration.*"`
![image2020-8-7 17 0 22](https://user-images.githubusercontent.com/25167192/89852856-60a84400-dbc2-11ea-9331-6c2c1a14e9f8.png)

伪造jwt
![image2020-8-7 18 19 41](https://user-images.githubusercontent.com/25167192/89852979-b4b32880-dbc2-11ea-9ae2-a7d43ea31b59.png)
![image2020-8-7 18 27 7](https://user-images.githubusercontent.com/25167192/89853006-c4327180-dbc2-11ea-9f73-78e469d685e4.png)
![image2020-8-7 18 28 13](https://user-images.githubusercontent.com/25167192/89853037-d90f0500-dbc2-11ea-8571-b6f98c76f384.png)

**Comment by wxiaoqi** [comment]
spring boot actuator导出堆这个限制确实疏忽了，这个周末Fix后再验证看看。
