### ISSUE TITLE
ace-gate下依赖全报红是什么问题

### ISSUE THREAD

**Issue by fan-code** [wxiaoqi/Spring-Cloud-Platform#38]
ace-gate下依赖都是红的，pom文件中
        <dependency>
            <groupId>de.codecentric</groupId>
            <artifactId>spring-boot-admin-starter-client</artifactId>
            <version>2.0.1</version>
        </dependency>
这个也报红，是什么原因呢

**Comment by wxiaoqi** [comment]
检查下本地仓库是否正常
