### ISSUE TITLE
为什么这个项目start很多，但是提问题的很少

### ISSUE THREAD

**Issue by Gangchao** [wxiaoqi/Spring-Cloud-Platform#40]
这个项目是不是少了工程，一直权限有问题

**Comment by lihengcn** [comment]
是的

**Comment by wxiaoqi** [comment]
工程没有少，可以正常运行的

**Comment by lowyjoe** [comment]
嗯 可以运行，就是没有说明文档

**Comment by aboutZZ** [comment]
目前仍不看好国内开源项目, 代码质量较差, 刷star, 迎合大多数开发者代码习惯

**Comment by mybirthfather** [comment]
star 是买的？ 5.5k的星星的项目 issues 总共30多个 还说来看看呢。。。。好坑

**Comment by wxiaoqi** [comment]
这是来自QQ邮箱的假期自动回复邮件。同时麻烦你告知下我！我好去查收~~谢谢

**Comment by wxiaoqi** [comment]
> star 是买的？ 5.5k的星星的项目 issues 总共30多个 还说来看看呢。。。。好坑

坑你哪了呢？star还需要花钱买？🍋
