### ISSUE TITLE
前端菜单菜单管理无法显示菜单项

### ISSUE THREAD

**Issue by 570108392** [wxiaoqi/Spring-Cloud-Platform#43]
前端修改：
getList() {
      fetchTree(this.listQuery).then(data => {
        this.treeData = data
      });
    },
修改为：
getList() {
      fetchTree(this.listQuery).then(data => {
        this.treeData = data.data
      });
    },

或者直接修改后端接口返回

**Comment by wxiaoqi** [comment]
没有发现该问题，请检查前端版本是否最新的
